---
services:
  builder:
    image: ghcr.io/projectpotos/potos-iso-builder:4.0.0-rc.2
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    device_cgroup_rules:
      - "b 7:* rmw"
    devices:
      - /dev/loop-control
    volumes:
      - /dev:/dev
      - ./input:/input:ro
      - ./output:/output:z
    command:
      - --config
      - /input/config.yml
      - --input-dir
      - /input
      - --output-dir
      - /output
